#ifndef PRINTS_THE_WINNER_OF_THE_GAME_OR_IF_THE_GAME_WAS_A_TIE_H
#define PRINTS_THE_WINNER_OF_THE_GAME_OR_IF_THE_GAME_WAS_A_TIE_H

void prints_the_winner_of_the_game_or_if_the_game_was_a_tie();

#endif