#ifndef UPDATE_THE_CURRENT_DISPLAY_OF_THE_PLAYERS_ON_THE_BOARD_H
#define UPDATE_THE_CURRENT_DISPLAY_OF_THE_PLAYERS_ON_THE_BOARD_H

void update_the_current_display_of_the_players_on_the_board();

#endif